import os
import io
import re
import zipfile
import hashlib
import secrets
from datetime import datetime, date, timedelta
from urllib.parse import quote

import pandas as pd
import plotly.express as px
import streamlit as st
from sqlalchemy import create_engine, text

try:
    import requests
except Exception:
    requests = None

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
except Exception:
    colors = None

APP_VERSION = "V25.2 POS Rápido + Créditos Reales"
APP_NAME_DEFAULT = "Clomar Store"

st.set_page_config(
    page_title="Clomar Store",
    page_icon="🛍️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ============================================================
# DB / CONFIG
# ============================================================
def get_secret(name: str, default=None):
    try:
        if name in st.secrets:
            return st.secrets[name]
    except Exception:
        pass
    return os.getenv(name, default)


def database_url():
    return get_secret("NEON_DATABASE_URL") or get_secret("DATABASE_URL") or "sqlite:///clomar_store_cloud_local.db"


DB_URL = database_url()
IS_POSTGRES = DB_URL.startswith("postgresql")
IS_LOCAL_SQLITE = DB_URL.startswith("sqlite")


@st.cache_resource(show_spinner=False)
def get_engine(url: str):
    if url.startswith("sqlite"):
        return create_engine(url, pool_pre_ping=True, connect_args={"check_same_thread": False, "timeout": 60})
    return create_engine(url, pool_pre_ping=True, pool_size=3, max_overflow=5, pool_recycle=1800)


ENGINE = get_engine(DB_URL)


def id_sql():
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if IS_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"


def exec_sql(sql: str, params: dict | None = None):
    with ENGINE.begin() as conn:
        return conn.execute(text(sql), params or {})


def query_df(sql: str, params: dict | None = None) -> pd.DataFrame:
    with ENGINE.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params or {})


def scalar(sql: str, params: dict | None = None, default=0):
    try:
        with ENGINE.connect() as conn:
            v = conn.execute(text(sql), params or {}).scalar()
        return default if v is None else v
    except Exception:
        return default


def safe_alter(table: str, column_sql: str):
    try:
        exec_sql(f"ALTER TABLE {table} ADD COLUMN {column_sql}")
    except Exception:
        pass


def init_db():
    ddl = [
        f"""
        CREATE TABLE IF NOT EXISTS usuarios (
            id_usuario {id_sql()},
            usuario VARCHAR(80) UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            nombre VARCHAR(160) NOT NULL,
            rol VARCHAR(40) NOT NULL DEFAULT 'Vendedor',
            estado VARCHAR(30) NOT NULL DEFAULT 'Activo',
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS categorias (
            id_categoria {id_sql()},
            nombre_categoria VARCHAR(160) UNIQUE NOT NULL,
            descripcion TEXT DEFAULT '',
            estado VARCHAR(30) DEFAULT 'Activo',
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS clientes (
            id_cliente {id_sql()},
            nombre_cliente VARCHAR(200) NOT NULL,
            telefono VARCHAR(80) DEFAULT '',
            documento VARCHAR(80) DEFAULT '',
            direccion TEXT DEFAULT '',
            observacion TEXT DEFAULT '',
            limite_credito NUMERIC(12,2) DEFAULT 0,
            estado VARCHAR(30) DEFAULT 'Activo',
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS proveedores (
            id_proveedor {id_sql()},
            nombre_proveedor VARCHAR(200) NOT NULL,
            telefono VARCHAR(80) DEFAULT '',
            documento VARCHAR(80) DEFAULT '',
            direccion TEXT DEFAULT '',
            estado VARCHAR(30) DEFAULT 'Activo',
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS productos (
            id_producto {id_sql()},
            codigo VARCHAR(80) UNIQUE,
            nombre_producto VARCHAR(240) NOT NULL,
            id_categoria INTEGER,
            marca VARCHAR(120) DEFAULT '',
            descripcion TEXT DEFAULT '',
            unidad VARCHAR(60) DEFAULT 'Unidad',
            costo_unitario NUMERIC(12,2) DEFAULT 0,
            precio_venta NUMERIC(12,2) DEFAULT 0,
            stock_minimo NUMERIC(12,2) DEFAULT 0,
            imagen_url TEXT DEFAULT '',
            estado VARCHAR(30) DEFAULT 'Activo',
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS movimientos_stock (
            id_movimiento {id_sql()},
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            id_producto INTEGER,
            tipo VARCHAR(60),
            cantidad NUMERIC(12,2) DEFAULT 0,
            costo_unitario NUMERIC(12,2) DEFAULT 0,
            referencia VARCHAR(120) DEFAULT '',
            id_usuario INTEGER,
            observacion TEXT DEFAULT ''
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS ventas (
            id_venta {id_sql()},
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            comprobante VARCHAR(80) UNIQUE,
            id_cliente INTEGER,
            id_usuario INTEGER,
            vendedor_nombre VARCHAR(160),
            metodo_pago VARCHAR(60),
            total_venta NUMERIC(12,2) DEFAULT 0,
            monto_pagado NUMERIC(12,2) DEFAULT 0,
            saldo_pendiente NUMERIC(12,2) DEFAULT 0,
            estado_pago VARCHAR(30) DEFAULT 'Pagada',
            observacion TEXT DEFAULT '',
            anulada INTEGER DEFAULT 0
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS detalle_ventas (
            id_detalle {id_sql()},
            id_venta INTEGER,
            id_producto INTEGER,
            producto_nombre VARCHAR(240),
            cantidad NUMERIC(12,2),
            precio_unitario NUMERIC(12,2),
            costo_unitario NUMERIC(12,2),
            subtotal NUMERIC(12,2)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS caja (
            id_caja {id_sql()},
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            tipo VARCHAR(60) DEFAULT 'Ingreso',
            concepto TEXT,
            metodo_pago VARCHAR(60),
            monto NUMERIC(12,2) DEFAULT 0,
            referencia VARCHAR(120) DEFAULT '',
            id_usuario INTEGER,
            observacion TEXT DEFAULT '',
            anulada INTEGER DEFAULT 0
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS pagos_credito (
            id_pago {id_sql()},
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            id_venta INTEGER NOT NULL,
            id_cliente INTEGER,
            metodo_pago VARCHAR(60) DEFAULT 'Efectivo',
            monto NUMERIC(12,2) DEFAULT 0,
            referencia VARCHAR(120) DEFAULT '',
            id_usuario INTEGER,
            observacion TEXT DEFAULT ''
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS compras (
            id_compra {id_sql()},
            fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            proveedor VARCHAR(200) DEFAULT '',
            total_compra NUMERIC(12,2) DEFAULT 0,
            monto_pagado NUMERIC(12,2) DEFAULT 0,
            metodo_pago VARCHAR(60) DEFAULT 'Efectivo',
            observacion TEXT DEFAULT '',
            id_usuario INTEGER
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS ajustes (
            clave VARCHAR(120) PRIMARY KEY,
            valor TEXT DEFAULT ''
        )
        """,
    ]
    for s in ddl:
        exec_sql(s)

    # Migraciones suaves para tablas antiguas
    safe_alter("productos", "descripcion TEXT DEFAULT ''")
    safe_alter("productos", "imagen_url TEXT DEFAULT ''")
    safe_alter("productos", "actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    safe_alter("ventas", "anulada INTEGER DEFAULT 0")
    safe_alter("ventas", "fecha_vencimiento DATE")
    safe_alter("ventas", "tipo_venta VARCHAR(40) DEFAULT 'Contado'")
    safe_alter("caja", "anulada INTEGER DEFAULT 0")

    if scalar("SELECT COUNT(*) FROM usuarios") == 0:
        exec_sql("""
            INSERT INTO usuarios (usuario,password_hash,nombre,rol,estado)
            VALUES (:u,:p,:n,:r,'Activo')
        """, {"u": "admin", "p": hash_password("admin123"), "n": "Administrador", "r": "Administrador"})
        exec_sql("""
            INSERT INTO usuarios (usuario,password_hash,nombre,rol,estado)
            VALUES (:u,:p,:n,:r,'Activo')
        """, {"u": "vendedor", "p": hash_password("venta123"), "n": "Vendedor", "r": "Vendedor"})

    for k, v in {
        "store_name": "Clomar Store",
        "logo_url": "",
        "icon_url": "",
        "telefono": "",
        "direccion": "",
        "mensaje_comprobante": "Gracias por su compra.",
        "color_principal": "#0f172a",
        "catalogo_base_url": "https://clomar-store.streamlit.app",
        "imagenes_base_url": "https://raw.githubusercontent.com/CLOMARstore/clomar-store/main/imagenes_productos",
        "whatsapp_codigo_pais": "51",
    }.items():
        try:
            exec_sql("INSERT INTO ajustes (clave, valor) VALUES (:k,:v)", {"k": k, "v": v})
        except Exception:
            pass


# ============================================================
# SEGURIDAD / UTILIDADES
# ============================================================
def hash_password(password: str) -> str:
    salt = secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac("sha256", str(password).encode(), salt.encode(), 120_000).hex()
    return f"pbkdf2_sha256${salt}${digest}"


def verify_password(password: str, stored_hash: str | None) -> bool:
    if not stored_hash:
        return False
    stored_hash = str(stored_hash)
    if stored_hash.startswith("pbkdf2_sha256$"):
        try:
            _, salt, digest = stored_hash.split("$", 2)
            candidate = hashlib.pbkdf2_hmac("sha256", str(password).encode(), salt.encode(), 120_000).hex()
            return secrets.compare_digest(candidate, digest)
        except Exception:
            return False
    legacy = hashlib.sha256(str(password).encode("utf-8")).hexdigest()
    return secrets.compare_digest(legacy, stored_hash)


def money(x) -> str:
    try:
        return f"S/ {float(x or 0):,.2f}".replace(",", "_").replace(".", ",").replace("_", ".")
    except Exception:
        return "S/ 0,00"


def num(x) -> str:
    try:
        return f"{float(x or 0):,.2f}".replace(",", "_").replace(".", ",").replace("_", ".")
    except Exception:
        return "0,00"


def esc(x):
    return str(x or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def settings() -> dict:
    try:
        df = query_df("SELECT clave, valor FROM ajustes")
        return {r["clave"]: r["valor"] for _, r in df.iterrows()}
    except Exception:
        return {}


@st.cache_data(ttl=300, show_spinner=False)
def cached_settings() -> dict:
    return settings()


def get_setting(k, default=""):
    return cached_settings().get(k, default)


def set_setting(k, v):
    try:
        exec_sql("UPDATE ajustes SET valor=:v WHERE clave=:k", {"k": k, "v": str(v or "")})
        if scalar("SELECT COUNT(*) FROM ajustes WHERE clave=:k", {"k": k}) == 0:
            exec_sql("INSERT INTO ajustes (clave, valor) VALUES (:k,:v)", {"k": k, "v": str(v or "")})
        cached_settings.clear()
    except Exception:
        pass


def current_user():
    return st.session_state.get("user")


def is_admin():
    u = current_user() or {}
    return str(u.get("rol", "")).lower() in ["administrador", "admin", "dueño", "propietario", "supervisor"]


def user_is_vendor():
    return not is_admin()


def normalize_code(c):
    s = str(c or "").strip()
    if s.endswith(".0"):
        s = s[:-2]
    return s


def wa_link(producto: str = ""):
    tel = re.sub(r"\D+", "", str(get_setting("telefono", "")))
    if tel and not tel.startswith("51") and len(tel) == 9:
        tel = str(get_setting("whatsapp_codigo_pais", "51")) + tel
    msg = f"Hola, deseo consultar por {producto}" if producto else "Hola, deseo consultar productos de Clomar Store"
    return f"https://wa.me/{tel}?text={quote(msg)}" if tel else "#"


def product_image_url(row_or_dict) -> str:
    d = dict(row_or_dict)
    url = str(d.get("imagen_url") or "").strip()
    if url.startswith("http://") or url.startswith("https://"):
        return url
    codigo = normalize_code(d.get("codigo"))
    if not codigo:
        return ""
    base = str(get_setting("imagenes_base_url", "")).strip().rstrip("/")
    if not base:
        return ""
    return f"{base}/{codigo}.jpg"


def product_image_candidates(row_or_dict) -> list[str]:
    d = dict(row_or_dict)
    explicit = str(d.get("imagen_url") or "").strip()
    if explicit.startswith("http://") or explicit.startswith("https://"):
        return [explicit]
    codigo = normalize_code(d.get("codigo"))
    base = str(get_setting("imagenes_base_url", "")).strip().rstrip("/")
    if not codigo or not base:
        return []
    # Soporta nombres habituales: 0001.jpg, 0001.png, 0001.jpeg, 0001.JPG
    return [f"{base}/{codigo}.jpg", f"{base}/{codigo}.png", f"{base}/{codigo}.jpeg", f"{base}/{codigo}.JPG"]


def stock_expr_sql():
    return """
        COALESCE(SUM(CASE
            WHEN ms.tipo IN ('ENTRADA','ENTRADA_COMPRA','AJUSTE_POSITIVO') THEN ms.cantidad
            WHEN ms.tipo IN ('SALIDA','SALIDA_VENTA','AJUSTE_NEGATIVO') THEN -ms.cantidad
            WHEN ms.tipo = 'AJUSTE' THEN ms.cantidad
            ELSE 0 END),0)
    """


@st.cache_data(ttl=120, show_spinner=False)
def productos_con_stock_cached():
    return query_df(f"""
        SELECT p.*, COALESCE(c.nombre_categoria,'Sin categoría') AS categoria,
               {stock_expr_sql()} AS stock_actual
        FROM productos p
        LEFT JOIN categorias c ON c.id_categoria=p.id_categoria
        LEFT JOIN movimientos_stock ms ON ms.id_producto=p.id_producto
        WHERE COALESCE(p.estado,'Activo')='Activo'
        GROUP BY p.id_producto, p.codigo, p.nombre_producto, p.id_categoria, p.marca, p.descripcion,
                 p.unidad, p.costo_unitario, p.precio_venta, p.stock_minimo, p.imagen_url, p.estado,
                 p.creado_en, p.actualizado_en, c.nombre_categoria
        ORDER BY p.nombre_producto
    """)


def productos_con_stock():
    return productos_con_stock_cached().copy()


def clear_product_cache():
    productos_con_stock_cached.clear()


@st.cache_data(ttl=60, show_spinner=False)
def ventas_periodo_cached(desde: str, hasta: str):
    return query_df("""
        SELECT v.*, COALESCE(c.nombre_cliente,'Cliente general') AS cliente
        FROM ventas v
        LEFT JOIN clientes c ON c.id_cliente=v.id_cliente
        WHERE DATE(v.fecha) BETWEEN :d AND :h AND COALESCE(v.anulada,0)=0
        ORDER BY v.fecha DESC
    """, {"d": desde, "h": hasta})


def ventas_periodo(desde, hasta):
    return ventas_periodo_cached(str(desde), str(hasta)).copy()


@st.cache_data(ttl=60, show_spinner=False)
def detalle_productos_vendidos_cached(desde: str, hasta: str):
    return query_df("""
        SELECT v.vendedor_nombre AS vendedor, dv.producto_nombre AS producto,
               SUM(dv.cantidad) AS cantidad,
               SUM(dv.subtotal) AS total_vendido,
               SUM((dv.precio_unitario - COALESCE(dv.costo_unitario,0))*dv.cantidad) AS utilidad
        FROM detalle_ventas dv
        JOIN ventas v ON v.id_venta=dv.id_venta
        WHERE DATE(v.fecha) BETWEEN :d AND :h AND COALESCE(v.anulada,0)=0
        GROUP BY v.vendedor_nombre, dv.producto_nombre
        ORDER BY total_vendido DESC
    """, {"d": desde, "h": hasta})


def detalle_productos_vendidos(desde, hasta):
    return detalle_productos_vendidos_cached(str(desde), str(hasta)).copy()


def clear_report_cache():
    ventas_periodo_cached.clear()
    detalle_productos_vendidos_cached.clear()


# ============================================================
# ESTILOS
# ============================================================
def inject_css():
    color = get_setting("color_principal", "#0f172a") or "#0f172a"
    st.markdown(f"""
    <style>
    :root {{ --primary:{color}; --dark:#0f172a; --muted:#64748b; --line:#e5e7eb; --bg:#f6f8fc; --danger:#ef4444; --ok:#16a34a; }}
    .stApp {{ background:#f6f8fc; color:#111827; }}
    header[data-testid="stHeader"] {{ background:#0b0f19; }}
    .block-container {{ padding-top:1.05rem; padding-bottom:2.4rem; max-width:1500px; }}
    section[data-testid="stSidebar"] {{ background:#ffffff; border-right:1px solid #e5e7eb; }}
    section[data-testid="stSidebar"] * {{ color:#111827 !important; opacity:1 !important; }}
    section[data-testid="stSidebar"] button {{ background:#ffffff !important; color:#111827 !important; border:1px solid #e5e7eb !important; }}
    .sidebar-logo {{ display:flex; align-items:center; gap:10px; margin:8px 0 18px; }}
    .sidebar-logo img {{ width:38px; height:38px; object-fit:contain; border-radius:10px; }}
    .sidebar-title {{ font-size:20px; font-weight:900; color:#111827 !important; }}
    .clomar-hero {{ background:linear-gradient(135deg,#111827,#1e293b); border-radius:0 0 22px 22px; padding:28px 34px; margin-bottom:24px; box-shadow:0 16px 34px rgba(15,23,42,.14); }}
    .clomar-hero, .clomar-hero * {{ color:#ffffff !important; opacity:1 !important; }}
    .clomar-hero h1 {{ margin:0; font-size:38px; line-height:1.08; font-weight:950; letter-spacing:-.02em; }}
    .clomar-hero p {{ margin:13px 0 0; color:#e5e7eb !important; font-size:16px; }}
    .card, .product-card, .kpi-card, .receipt-box {{ background:#fff; border:1px solid #e5e7eb; border-radius:20px; padding:20px; box-shadow:0 8px 25px rgba(15,23,42,.06); }}
    .kpi-label {{ color:#6b7280; font-size:13px; font-weight:900; letter-spacing:.06em; text-transform:uppercase; }}
    .kpi-value {{ color:#0f172a; font-size:34px; font-weight:950; margin-top:12px; }}
    .product-card {{ overflow:hidden; min-height:330px; display:flex; flex-direction:column; gap:9px; }}
    .product-img-wrap {{ width:100%; height:190px; background:linear-gradient(135deg,#fff7ed,#fdf2f8); border:1px solid #eef2f7; border-radius:16px; overflow:hidden; display:flex; align-items:center; justify-content:center; margin-bottom:8px; }}
    .product-img-wrap.no-img::after {{ content:'🛍️'; font-size:58px; opacity:.65; }}
    .product-img {{ width:100%; height:100%; object-fit:cover; display:block; }}
    .product-name {{ font-weight:950; font-size:18px; line-height:1.3; color:#111827; }}
    .product-meta {{ color:#64748b; font-size:13px; line-height:1.45; }}
    .product-desc {{ color:#64748b; font-size:13px; line-height:1.35; min-height:20px; }}
    .product-price {{ font-size:28px; font-weight:950; color:#0f172a; margin-top:6px; }}
    .chip {{ display:inline-block; border-radius:999px; padding:7px 12px; font-weight:900; font-size:12px; margin:3px 4px 0 0; border:1px solid #e5e7eb; background:#f8fafc; color:#111827; }}
    .chip-ok {{ background:#dcfce7; color:#166534; border-color:#bbf7d0; }}
    .chip-red {{ background:#fee2e2; color:#991b1b; border-color:#fecaca; }}
    .chip-dark {{ background:#0f172a; color:#fff; border-color:#0f172a; }}
    .chip-warn {{ background:#fef3c7; color:#92400e; border-color:#fde68a; }}
    .success-panel {{ background:#fff; border:1px solid #e5e7eb; border-radius:24px; padding:36px; text-align:center; box-shadow:0 10px 30px rgba(15,23,42,.08); margin:22px 0; }}
    .success-icon {{ font-size:52px; }} .success-title {{ font-size:32px; font-weight:950; color:#0f172a; }} .success-sub {{ color:#64748b; font-size:16px; }}
    .public-wrap {{ max-width:1180px; margin:0 auto; }}
    div[data-testid="stTextInput"] input, div[data-testid="stNumberInput"] input, div[data-testid="stTextArea"] textarea, div[data-testid="stSelectbox"] div[data-baseweb="select"] > div, div[data-testid="stDateInput"] input {{
        background:#ffffff !important; color:#111827 !important; border:1px solid #cbd5e1 !important; border-radius:12px !important;
    }}
    div[data-testid="stWidgetLabel"], div[data-testid="stWidgetLabel"] *, label {{ color:#111827 !important; opacity:1 !important; font-weight:800 !important; }}
    .stMarkdown:not(.clomar-hero) p, .stMarkdown:not(.clomar-hero) span {{ color:inherit; }}
    .stButton > button, .stDownloadButton > button {{ border-radius:12px !important; min-height:44px; font-weight:900 !important; color:#111827 !important; background:#ffffff !important; border:1px solid #cbd5e1 !important; }}
    .stButton > button[kind="primary"], .stDownloadButton > button[kind="primary"] {{ background:#0f172a !important; color:#fff !important; border:1px solid #0f172a !important; }}
    .stButton > button[kind="primary"] *, .stDownloadButton > button[kind="primary"] * {{ color:#fff !important; }}
    .stButton > button:hover, .stDownloadButton > button:hover {{ filter:brightness(.98); border-color:#0f172a !important; }}
    div[data-testid="stAlert"] {{ border-radius:14px; color:#111827 !important; }}
    .dataframe, table {{ color:#111827 !important; }}
    .clomar-table {{ width:100%; border-collapse:collapse; background:#fff; border-radius:18px; overflow:hidden; box-shadow:0 8px 25px rgba(15,23,42,.06); }}
    .clomar-table th {{ background:#f8fafc; color:#475569; text-align:left; padding:14px; font-size:12px; text-transform:uppercase; letter-spacing:.06em; }}
    .clomar-table td {{ padding:14px; border-top:1px solid #eef2f7; color:#111827; }}
    .small-note {{ color:#64748b; font-size:13px; }}
    .pos-card {{ background:#fff; border:1px solid #e5e7eb; border-radius:16px; padding:14px; margin-bottom:10px; box-shadow:0 6px 18px rgba(15,23,42,.05); }}
    .pos-title {{ color:#111827; font-weight:950; font-size:16px; line-height:1.25; }}
    .pos-meta {{ color:#64748b; font-size:12px; margin-top:3px; }}
    .pos-price {{ color:#0f172a; font-size:22px; font-weight:950; margin:8px 0; }}
    .cart-line {{ background:#fff; border:1px solid #e5e7eb; border-radius:14px; padding:12px; margin-bottom:10px; }}
    .pay-box {{ background:#fff; border:1px solid #e5e7eb; border-radius:20px; padding:18px; box-shadow:0 8px 25px rgba(15,23,42,.06); }}
    .receipt-actions {{ display:flex; gap:10px; flex-wrap:wrap; margin-top:12px; }}
    .print-button {{ background:#0f172a; color:white !important; border:0; border-radius:12px; padding:12px 18px; font-weight:900; cursor:pointer; }}
    @media (max-width: 900px) {{ .clomar-hero h1 {{font-size:30px;}} .product-img-wrap {{height:155px;}} .block-container {{padding-left:.75rem; padding-right:.75rem;}} }}
    </style>
    """, unsafe_allow_html=True)


def html_table(df: pd.DataFrame, cols: list[str], labels: list[str], limit=100):
    if df.empty:
        st.info("Sin registros.")
        return
    rows = []
    for _, r in df.head(limit).iterrows():
        tds = "".join(f"<td>{esc(r.get(c,''))}</td>" for c in cols)
        rows.append(f"<tr>{tds}</tr>")
    th = "".join(f"<th>{esc(x)}</th>" for x in labels)
    st.markdown(f"<table class='clomar-table'><thead><tr>{th}</tr></thead><tbody>{''.join(rows)}</tbody></table>", unsafe_allow_html=True)


def kpi(label, value, sub=""):
    st.markdown(f"<div class='kpi-card'><div class='kpi-label'>{esc(label)}</div><div class='kpi-value'>{esc(value)}</div><div class='product-meta'>{esc(sub)}</div></div>", unsafe_allow_html=True)


def hero(title, subtitle, icon=""):
    st.markdown(f"<div class='clomar-hero'><h1>{icon} {esc(title)}</h1><p>{esc(subtitle)}</p></div>", unsafe_allow_html=True)


# ============================================================
# LOGIN / SIDEBAR
# ============================================================
def login_screen():
    cfg = cached_settings()
    logo = cfg.get("logo_url", "")
    icon = cfg.get("icon_url", "") or logo
    store = cfg.get("store_name") or APP_NAME_DEFAULT
    st.markdown("""
    <div style='max-width:520px;margin:28px auto 8px auto;'>
      <div class='card' style='padding:28px 30px;'>
    """, unsafe_allow_html=True)
    if logo:
        st.markdown(f"<div style='text-align:center;margin-bottom:12px'><img src='{esc(logo)}' style='max-width:240px;max-height:95px;object-fit:contain'></div>", unsafe_allow_html=True)
    elif icon:
        st.markdown(f"<div style='text-align:center;margin-bottom:12px'><img src='{esc(icon)}' style='width:82px;height:82px;object-fit:contain'></div>", unsafe_allow_html=True)
    st.markdown(f"<h2 style='margin:0 0 18px;color:#111827;font-weight:950;text-align:center'>Iniciar sesión</h2>", unsafe_allow_html=True)
    usuario = st.text_input("Usuario", placeholder="admin o vendedor")
    clave = st.text_input("Contraseña", type="password", placeholder="Tu contraseña")
    if st.button("Entrar", type="primary", use_container_width=True):
        df = query_df("SELECT * FROM usuarios WHERE usuario=:u AND estado='Activo'", {"u": usuario.strip()})
        if df.empty or not verify_password(clave, df.iloc[0]["password_hash"]):
            st.error("Usuario o contraseña incorrectos.")
        else:
            row = df.iloc[0].to_dict()
            st.session_state.user = {
                "id_usuario": int(row["id_usuario"]), "usuario": row["usuario"],
                "nombre": row["nombre"], "rol": row["rol"]
            }
            st.rerun()
    st.markdown("<div class='small-note' style='text-align:center;margin-top:14px'>Acceso seguro. Usa las credenciales definidas por el administrador.</div>", unsafe_allow_html=True)
    st.markdown("</div></div>", unsafe_allow_html=True)

def sidebar_nav():
    u = current_user()
    cfg = cached_settings()
    logo = cfg.get("icon_url") or cfg.get("logo_url")
    store = cfg.get("store_name") or APP_NAME_DEFAULT
    if logo:
        st.sidebar.markdown(f"<div class='sidebar-logo'><img src='{esc(logo)}'><div class='sidebar-title'>{esc(store)}</div></div>", unsafe_allow_html=True)
    else:
        st.sidebar.markdown(f"### 🛍️ {store}")
    st.sidebar.caption(f"{u['nombre']} · {u['rol']}")
    if is_admin():
        opciones = [
            "📊 Panel dueño", "🧾 Ventas", "💳 Créditos", "📦 Productos", "📘 Catálogo clientes", "📊 Inventario", "📥 Ingreso mercadería", "👥 Clientes", "💰 Caja", "📈 Reportes", "🔐 Usuarios", "⚙️ Configuración", "💾 Backup", "📲 Instalar app", "☁️ Estado nube"
        ]
    else:
        opciones = ["🧾 Ventas", "👥 Clientes", "📦 Productos", "📘 Catálogo clientes", "📲 Instalar app"]
    selected = st.sidebar.radio("Menú", opciones, label_visibility="collapsed")
    st.sidebar.divider()
    if st.sidebar.button("Cerrar sesión", use_container_width=True):
        st.session_state.clear()
        st.rerun()
    return selected


# ============================================================
# COMPONENTES PRODUCTO / RECIBO / PDF
# ============================================================
def product_card_html(r, show_cost=False, show_stock=True, whatsapp=False):
    img_candidates = product_image_candidates(r)
    img = img_candidates[0] if img_candidates else ""
    stock = float(r.get("stock_actual") or 0)
    stock_min = float(r.get("stock_minimo") or 0)
    chip_stock = ""
    if show_stock:
        chip_stock = f"<span class='chip {'chip-ok' if stock > stock_min else 'chip-red'}'>Stock {num(stock)}</span>"
    chip_cost = f"<span class='chip chip-dark'>Costo {money(r.get('costo_unitario'))}</span>" if show_cost else ""
    desc = esc(str(r.get("descripcion") or "")[:120])
    img_html = f"<img class='product-img' src='{esc(img)}' onerror=\"this.style.display='none';this.parentElement.classList.add('no-img');\">" if img else ""
    wa = f"<a href='{esc(wa_link(r.get('nombre_producto')))}' target='_blank' style='text-decoration:none'><div class='chip chip-dark' style='text-align:center;width:100%;box-sizing:border-box;margin-top:8px'>💬 Consultar por WhatsApp</div></a>" if whatsapp else ""
    return f"""
    <div class='product-card'>
      <div class='product-img-wrap'>{img_html}</div>
      <div class='product-name'>{esc(r.get('nombre_producto'))}</div>
      <div class='product-meta'>{esc(r.get('codigo'))} · {esc(r.get('categoria'))}</div>
      <div class='product-desc'>{desc}</div>
      <div class='product-price'>{money(r.get('precio_venta'))}</div>
      <div>{chip_stock}{chip_cost}</div>
      {wa}
    </div>
    """


def add_product_button(r, keyprefix="add"):
    stock = float(r.get("stock_actual") or 0)
    disabled = stock <= 0
    label = "🛒 Agregar" if stock > 0 else "Sin stock"
    if st.button(label, key=f"{keyprefix}_{r['id_producto']}", use_container_width=True, disabled=disabled):
        if "cart" not in st.session_state:
            st.session_state.cart = []
        found = False
        for item in st.session_state.cart:
            if item["id_producto"] == int(r["id_producto"]):
                item["cantidad"] += 1
                found = True
                break
        if not found:
            st.session_state.cart.append({
                "id_producto": int(r["id_producto"]), "nombre": r["nombre_producto"], "codigo": r.get("codigo", ""),
                "precio": float(r["precio_venta"] or 0), "costo": float(r["costo_unitario"] or 0), "stock": stock, "cantidad": 1.0
            })
        st.toast("Producto agregado al carrito")
        st.rerun()


def render_receipt(id_venta: int):
    venta = query_df("""
        SELECT v.*, COALESCE(c.nombre_cliente,'Cliente general') AS cliente
        FROM ventas v LEFT JOIN clientes c ON c.id_cliente=v.id_cliente
        WHERE v.id_venta=:id
    """, {"id": id_venta})
    if venta.empty:
        return
    v = venta.iloc[0]
    det = query_df("SELECT * FROM detalle_ventas WHERE id_venta=:id", {"id": id_venta})
    cfg = cached_settings()
    rows = "".join([f"<tr><td>{esc(r['producto_nombre'])}</td><td>{num(r['cantidad'])}</td><td>{money(r['precio_unitario'])}</td><td>{money(r['subtotal'])}</td></tr>" for _, r in det.iterrows()])
    logo = cfg.get("logo_url", "")
    logo_html = f"<img src='{esc(logo)}' style='max-width:150px;max-height:70px;object-fit:contain'>" if logo else ""
    st.markdown(f"""
    <div class='receipt-box'>
      {logo_html}
      <h3>{esc(cfg.get('store_name') or APP_NAME_DEFAULT)}</h3>
      <div class='product-meta'>{esc(cfg.get('direccion',''))} · {esc(cfg.get('telefono',''))}</div>
      <hr>
      <b>Comprobante:</b> {esc(v['comprobante'])}<br>
      <b>Fecha:</b> {esc(v['fecha'])}<br>
      <b>Cliente:</b> {esc(v['cliente'])}<br>
      <b>Vendedor:</b> {esc(v['vendedor_nombre'])}<br><br>
      <table class='clomar-table'><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>{rows}</tbody></table>
      <h2>Total: {money(v['total_venta'])}</h2>
      <div class='product-meta'>{esc(cfg.get('mensaje_comprobante','Gracias por su compra.'))}</div>
    </div>
    """, unsafe_allow_html=True)



def generate_receipt_pdf(id_venta: int):
    if colors is None:
        return None
    venta = query_df("""
        SELECT v.*, COALESCE(c.nombre_cliente,'Cliente general') AS cliente
        FROM ventas v LEFT JOIN clientes c ON c.id_cliente=v.id_cliente
        WHERE v.id_venta=:id
    """, {"id": id_venta})
    if venta.empty:
        return None
    v = venta.iloc[0]
    det = query_df("SELECT * FROM detalle_ventas WHERE id_venta=:id", {"id": id_venta})
    cfg = cached_settings()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=1.2*cm, leftMargin=1.2*cm, topMargin=1.1*cm, bottomMargin=1.1*cm)
    styles = getSampleStyleSheet()
    title = ParagraphStyle('ReceiptTitle', parent=styles['Title'], fontSize=18, leading=22, textColor=colors.HexColor('#0f172a'))
    normal = ParagraphStyle('ReceiptNormal', parent=styles['Normal'], fontSize=9, leading=12, textColor=colors.HexColor('#111827'))
    story = []
    story.append(Paragraph(str(cfg.get('store_name') or APP_NAME_DEFAULT), title))
    if cfg.get('direccion'):
        story.append(Paragraph(str(cfg.get('direccion')), normal))
    if cfg.get('telefono'):
        story.append(Paragraph(f"WhatsApp/Teléfono: {cfg.get('telefono')}", normal))
    story.append(Spacer(1, 0.25*cm))
    story.append(Paragraph(f"<b>Comprobante:</b> {v['comprobante']}", normal))
    story.append(Paragraph(f"<b>Fecha:</b> {v['fecha']}", normal))
    story.append(Paragraph(f"<b>Cliente:</b> {v['cliente']}", normal))
    story.append(Paragraph(f"<b>Vendedor:</b> {v['vendedor_nombre']}", normal))
    story.append(Spacer(1, 0.25*cm))
    data = [["Producto", "Cant.", "Precio", "Subtotal"]]
    for _, r in det.iterrows():
        data.append([str(r['producto_nombre'])[:48], num(r['cantidad']), money(r['precio_unitario']), money(r['subtotal'])])
    tbl = Table(data, colWidths=[8.2*cm, 2.0*cm, 3.0*cm, 3.0*cm])
    tbl.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR',(0,0),(-1,0), colors.HexColor('#0f172a')),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
        ('FONTSIZE',(0,0),(-1,-1),8),
        ('GRID',(0,0),(-1,-1),0.25, colors.HexColor('#e5e7eb')),
        ('VALIGN',(0,0),(-1,-1),'TOP'),
        ('ALIGN',(1,1),(-1,-1),'RIGHT')
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.25*cm))
    story.append(Paragraph(f"<b>Total:</b> {money(v['total_venta'])}", title))
    story.append(Paragraph(f"<b>Pagado:</b> {money(v['monto_pagado'])} &nbsp;&nbsp; <b>Saldo:</b> {money(v['saldo_pendiente'])}", normal))
    if cfg.get('mensaje_comprobante'):
        story.append(Spacer(1, 0.2*cm))
        story.append(Paragraph(str(cfg.get('mensaje_comprobante')), normal))
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

def generate_catalog_pdf(df: pd.DataFrame):
    if colors is None:
        return None
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=1.2*cm, leftMargin=1.2*cm, topMargin=1.2*cm, bottomMargin=1.2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('T', parent=styles['Title'], textColor=colors.HexColor('#0f172a'), fontSize=22, leading=26)
    normal = ParagraphStyle('N', parent=styles['Normal'], textColor=colors.HexColor('#111827'), fontSize=9, leading=12)
    small = ParagraphStyle('S', parent=styles['Normal'], textColor=colors.HexColor('#64748b'), fontSize=8, leading=10)
    story = []
    cfg = cached_settings()
    story.append(Paragraph(esc(cfg.get('store_name') or APP_NAME_DEFAULT), title_style))
    story.append(Paragraph(f"Catálogo comercial · {esc(cfg.get('telefono',''))} · {esc(cfg.get('direccion',''))}", small))
    story.append(Spacer(1, .35*cm))
    data = []
    for _, r in df.iterrows():
        img_cell = Paragraph("🛍️", normal)
        img_url = product_image_url(r)
        if requests and img_url:
            try:
                resp = requests.get(img_url, timeout=2)
                if resp.ok and len(resp.content) < 2_000_000:
                    img_cell = RLImage(io.BytesIO(resp.content), width=2.6*cm, height=2.2*cm)
                
            except Exception:
                pass
        texto = Paragraph(f"<b>{esc(r.get('nombre_producto'))}</b><br/>{esc(r.get('codigo'))} · {esc(r.get('categoria'))}<br/><font color='#0f172a'><b>{money(r.get('precio_venta'))}</b></font><br/>{'Disponible' if float(r.get('stock_actual') or 0)>0 else 'Consultar disponibilidad'}", normal)
        data.append([img_cell, texto])
    if not data:
        data = [[Paragraph("Sin productos visibles", normal), ""]]
    table = Table(data, colWidths=[3.1*cm, 13.5*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,-1), colors.white), ('BOX',(0,0),(-1,-1),0.25,colors.HexColor('#e5e7eb')),
        ('INNERGRID',(0,0),(-1,-1),0.25,colors.HexColor('#e5e7eb')), ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
        ('LEFTPADDING',(0,0),(-1,-1),8), ('RIGHTPADDING',(0,0),(-1,-1),8), ('TOPPADDING',(0,0),(-1,-1),8), ('BOTTOMPADDING',(0,0),(-1,-1),8),
    ]))
    story.append(table)
    story.append(Spacer(1, .25*cm))
    story.append(Paragraph(esc(cfg.get('mensaje_comprobante','Gracias por su preferencia.')), small))
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


# ============================================================
# PÁGINAS
# ============================================================
def page_panel_dueno():
    hero("Panel del dueño", "Vista ejecutiva en tiempo real para controlar ventas, inventario y caja.", "📊")
    if not is_admin():
        st.warning("Solo administrador puede ver el panel del dueño.")
        return
    c1, c2 = st.columns(2)
    with c1:
        desde = st.date_input("Desde", date.today(), key="pd_desde")
    with c2:
        hasta = st.date_input("Hasta", date.today(), key="pd_hasta")
    ventas = ventas_periodo(desde, hasta)
    detalle = detalle_productos_vendidos(desde, hasta)
    productos = productos_con_stock()
    total = ventas["total_venta"].sum() if not ventas.empty else 0
    utilidad = detalle["utilidad"].sum() if not detalle.empty else 0
    ticket = total / len(ventas) if len(ventas) else 0
    caja = query_df("SELECT * FROM caja WHERE DATE(fecha) BETWEEN :d AND :h AND COALESCE(anulada,0)=0", {"d": str(desde), "h": str(hasta)})
    caja_neta = caja[caja["tipo"].astype(str).str.lower().eq("ingreso")]["monto"].sum() - caja[caja["tipo"].astype(str).str.lower().eq("egreso")]["monto"].sum() if not caja.empty else 0
    a,b,c,d = st.columns(4)
    with a: kpi("Ventas", money(total), f"{len(ventas)} comprobantes")
    with b: kpi("Utilidad estimada", money(utilidad), "Según costo registrado")
    with c: kpi("Ticket promedio", money(ticket), "Promedio por venta")
    with d: kpi("Caja neta", money(caja_neta), "Ingresos - egresos")
    x1,x2 = st.columns([1.4,1])
    with x1:
        st.subheader("Ventas recientes")
        if ventas.empty:
            st.info("Todavía no hay ventas en el período.")
        else:
            vv = ventas.copy()
            vv["total_fmt"] = vv["total_venta"].apply(money)
            html_table(vv, ["comprobante","fecha","cliente","vendedor_nombre","metodo_pago","total_fmt"], ["Comprobante","Fecha","Cliente","Vendedor","Pago","Total"], 8)
    with x2:
        st.subheader("Stock crítico")
        crit = productos[productos["stock_actual"].astype(float) <= productos["stock_minimo"].astype(float)] if not productos.empty else pd.DataFrame()
        if crit.empty:
            st.success("Sin productos críticos.")
        else:
            for _, r in crit.head(10).iterrows():
                st.markdown(f"<span class='chip chip-red'>⚠️ {esc(r['nombre_producto'])} · Stock {num(r['stock_actual'])}</span>", unsafe_allow_html=True)
    st.subheader("Productos vendidos")
    if detalle.empty:
        st.info("No hay detalle de productos vendidos.")
    else:
        top = detalle.head(10).copy()
        fig = px.bar(top, x="producto", y="total_vendido", title="Top productos por venta")
        fig.update_layout(plot_bgcolor="white", paper_bgcolor="white", font_color="#111827")
        st.plotly_chart(fig, use_container_width=True)


def page_ventas():
    hero("POS rápido", "Paso 1: arma el carrito. Paso 2: cobra contado o registra crédito. Paso 3: decide si imprimes.", "🧾")
    if "cart" not in st.session_state:
        st.session_state.cart = []
    if "pos_step" not in st.session_state:
        st.session_state.pos_step = "carrito"

    # Vista de venta terminada: no recarga productos; muestra solo comprobante y acciones.
    if st.session_state.get("show_success_sale") and st.session_state.get("last_sale_id"):
        venta_id = int(st.session_state.last_sale_id)
        vdf = query_df("SELECT comprobante,total_venta,monto_pagado,saldo_pendiente,estado_pago FROM ventas WHERE id_venta=:id", {"id": venta_id})
        saldo = float(vdf.iloc[0]["saldo_pendiente"] or 0) if not vdf.empty else 0
        st.markdown("<div class='success-panel'><div class='success-icon'>✅</div><div class='success-title'>¡Venta registrada!</div><div class='success-sub'>Ahora puedes imprimir, descargar o seguir vendiendo.</div></div>", unsafe_allow_html=True)
        render_receipt(venta_id)
        pdf = generate_receipt_pdf(venta_id)
        a,b,c,d = st.columns(4)
        with a:
            if pdf:
                st.download_button("⬇️ Descargar PDF", data=pdf, file_name=f"comprobante_{vdf.iloc[0]['comprobante'] if not vdf.empty else venta_id}.pdf", mime="application/pdf", use_container_width=True)
        with b:
            st.markdown("<button class='print-button' onclick='window.print()'>🖨️ Imprimir</button>", unsafe_allow_html=True)
        with c:
            if st.button("No imprimir", use_container_width=True):
                st.session_state.show_success_sale = False
                st.session_state.pos_step = "carrito"
                st.rerun()
        with d:
            if st.button("Seguir vendiendo", type="primary", use_container_width=True):
                st.session_state.show_success_sale = False
                st.session_state.pos_step = "carrito"
                st.rerun()
        if saldo > 0:
            st.warning(f"Esta venta quedó con saldo pendiente: {money(saldo)}. Revísala en 💳 Créditos.")
        return

    # Total actual del carrito
    total_cart = sum(float(i.get("cantidad", 0)) * float(i.get("precio", 0)) for i in st.session_state.cart)
    s1, s2, s3 = st.columns([1,1,1])
    with s1:
        kpi("Productos en carrito", str(len(st.session_state.cart)), "Edítalos antes de cobrar")
    with s2:
        kpi("Total actual", money(total_cart), "No se registra hasta confirmar")
    with s3:
        kpi("Paso", "Carrito" if st.session_state.pos_step == "carrito" else "Pago", "Flujo rápido POS")

    if st.session_state.pos_step == "carrito":
        productos = productos_con_stock()
        categorias = sorted([x for x in productos["categoria"].dropna().unique()]) if not productos.empty else []
        left, right = st.columns([1.65, 1])
        with left:
            f1, f2, f3 = st.columns([1.45, .75, .55])
            with f1:
                buscar = st.text_input("Buscar producto", placeholder="Nombre, código o marca...", key="buscar_venta_fast")
            with f2:
                cat = st.selectbox("Categoría", ["Todas"] + categorias, key="cat_venta_fast")
            with f3:
                solo_stock = st.toggle("Solo stock", value=True, key="stock_venta_fast")

            fil = productos.copy()
            if solo_stock and not fil.empty:
                fil = fil[fil["stock_actual"].astype(float) > 0]
            if buscar.strip():
                txt = buscar.lower().strip()
                fil = fil[
                    fil["nombre_producto"].astype(str).str.lower().str.contains(txt, na=False) |
                    fil["codigo"].astype(str).str.lower().str.contains(txt, na=False) |
                    fil["marca"].astype(str).str.lower().str.contains(txt, na=False)
                ]
            if cat != "Todas":
                fil = fil[fil["categoria"].eq(cat)]
            fil = fil.head(18)
            if fil.empty:
                st.info("No hay productos que coincidan.")
            else:
                st.caption("Vista rápida: se muestran máximo 18 productos para que no se ponga lenta. Usa el buscador para encontrar rápido.")
                cols = st.columns(3)
                for i, (_, r) in enumerate(fil.iterrows()):
                    with cols[i % 3]:
                        stock = float(r.get("stock_actual") or 0)
                        st.markdown(f"""
                        <div class='pos-card'>
                            <div class='pos-title'>{esc(r.get('nombre_producto'))}</div>
                            <div class='pos-meta'>{esc(r.get('codigo'))} · {esc(r.get('categoria'))}</div>
                            <div class='pos-price'>{money(r.get('precio_venta'))}</div>
                            <span class='chip {'chip-ok' if stock > float(r.get('stock_minimo') or 0) else 'chip-red'}'>Stock {num(stock)}</span>
                        </div>
                        """, unsafe_allow_html=True)
                        qty = st.number_input("Cantidad", min_value=1.0, max_value=max(stock,1.0), value=1.0, step=1.0, key=f"qty_fast_{r['id_producto']}", disabled=stock<=0)
                        if st.button("Agregar", key=f"add_fast_{r['id_producto']}", type="primary", use_container_width=True, disabled=stock<=0):
                            found = False
                            for item in st.session_state.cart:
                                if item["id_producto"] == int(r["id_producto"]):
                                    item["cantidad"] = min(float(item["cantidad"]) + float(qty), stock)
                                    found = True
                                    break
                            if not found:
                                st.session_state.cart.append({
                                    "id_producto": int(r["id_producto"]),
                                    "nombre": r["nombre_producto"],
                                    "codigo": r.get("codigo", ""),
                                    "precio": float(r["precio_venta"] or 0),
                                    "costo": float(r["costo_unitario"] or 0),
                                    "stock": stock,
                                    "cantidad": float(qty)
                                })
                            st.toast("Agregado al carrito")
                            st.rerun()
        with right:
            st.subheader("🛒 Carrito")
            if not st.session_state.cart:
                st.info("Agrega productos para vender.")
            else:
                total = 0.0
                nuevo_cart = []
                for idx, item in enumerate(st.session_state.cart):
                    st.markdown(f"<div class='cart-line'><b>{esc(item['nombre'])}</b><br><span class='product-meta'>{esc(item.get('codigo',''))} · Stock {num(item.get('stock',0))}</span></div>", unsafe_allow_html=True)
                    cc1, cc2, cc3 = st.columns([.85, .9, .35])
                    with cc1:
                        cant = st.number_input("Cant.", min_value=0.0, max_value=float(item["stock"]), value=float(item["cantidad"]), step=1.0, key=f"cant_pos_{idx}")
                    with cc2:
                        if is_admin():
                            precio = st.number_input("Precio", min_value=0.0, value=float(item["precio"]), step=1.0, key=f"precio_pos_{idx}")
                        else:
                            precio = float(item["precio"])
                            st.text_input("Precio", value=money(precio), disabled=True, key=f"precio_pos_view_{idx}")
                    with cc3:
                        if st.button("❌", key=f"del_pos_{idx}"):
                            cant = 0
                    if cant > 0:
                        item["cantidad"] = cant
                        item["precio"] = precio
                        total += cant * precio
                        nuevo_cart.append(item)
                    st.divider()
                st.session_state.cart = nuevo_cart
                st.markdown(f"### Total: {money(total)}")
                c1, c2 = st.columns(2)
                with c1:
                    if st.button("Vaciar", use_container_width=True):
                        st.session_state.cart = []
                        st.rerun()
                with c2:
                    if st.button("Continuar al pago", type="primary", use_container_width=True, disabled=total<=0):
                        st.session_state.pos_step = "pago"
                        st.rerun()

    else:
        st.subheader("💳 Pago de la venta")
        if not st.session_state.cart:
            st.warning("El carrito está vacío.")
            if st.button("Volver a productos"):
                st.session_state.pos_step = "carrito"
                st.rerun()
            return
        total = sum(float(i.get("cantidad", 0)) * float(i.get("precio", 0)) for i in st.session_state.cart)
        left, right = st.columns([1.1, .9])
        with left:
            st.markdown("<div class='pay-box'>", unsafe_allow_html=True)
            clientes = query_df("SELECT id_cliente, nombre_cliente, telefono FROM clientes WHERE COALESCE(estado,'Activo')='Activo' ORDER BY nombre_cliente")
            opciones_cliente = {"Cliente general": None}
            if not clientes.empty:
                opciones_cliente.update({f"{r['nombre_cliente']}" + (f" · {r['telefono']}" if str(r.get('telefono') or '').strip() else ""): int(r["id_cliente"]) for _, r in clientes.iterrows()})
            cliente_nombre = st.selectbox("Cliente", list(opciones_cliente.keys()), key="pay_cliente")
            tipo_venta = st.selectbox("Tipo de venta", ["Contado", "Crédito"], key="tipo_venta")
            metodos = ["Efectivo", "Yape", "Plin", "Transferencia", "Tarjeta", "Mixto"]
            metodo_pago = st.selectbox("Medio de pago", metodos, key="pay_metodo")
            if tipo_venta == "Contado":
                monto_pagado = st.number_input("Monto recibido", min_value=0.0, value=float(total), step=1.0, key="monto_contado")
                fecha_venc = None
                saldo = max(total - monto_pagado, 0)
                vuelto = max(monto_pagado - total, 0)
                kpi("Vuelto", money(vuelto), "Entrega al cliente")
            else:
                monto_pagado = st.number_input("Pago inicial", min_value=0.0, max_value=float(total), value=0.0, step=1.0, key="monto_credito")
                fecha_venc = st.date_input("Fecha de vencimiento", date.today() + timedelta(days=15), key="fecha_venc_credito")
                saldo = max(total - monto_pagado, 0)
                kpi("Saldo a crédito", money(saldo), "Se verá en Créditos")
            observacion = st.text_area("Observación", placeholder="Pedido, entrega, nota interna...", key="obs_pago")
            a,b = st.columns(2)
            with a:
                if st.button("← Volver al carrito", use_container_width=True):
                    st.session_state.pos_step = "carrito"
                    st.rerun()
            with b:
                confirmar = st.button("Confirmar venta", type="primary", use_container_width=True)
            st.markdown("</div>", unsafe_allow_html=True)
        with right:
            st.markdown("<div class='pay-box'>", unsafe_allow_html=True)
            st.markdown("### Resumen")
            for item in st.session_state.cart:
                st.write(f"{num(item['cantidad'])} x {item['nombre']} — {money(float(item['cantidad'])*float(item['precio']))}")
            st.divider()
            kpi("Total a cobrar", money(total))
            kpi("Pagado", money(monto_pagado))
            kpi("Saldo", money(saldo))
            st.markdown("</div>", unsafe_allow_html=True)

        if confirmar:
            if total <= 0:
                st.error("El total debe ser mayor a cero.")
                return
            if tipo_venta == "Contado" and monto_pagado < total:
                st.error("En contado, el monto recibido debe cubrir el total. Si quedará deuda, cambia a Crédito.")
                return
            if tipo_venta == "Crédito" and opciones_cliente[cliente_nombre] is None:
                st.error("Para vender a crédito debes seleccionar un cliente registrado. No uses Cliente general.")
                return
            u = current_user()
            comprobante = f"V{datetime.now().strftime('%Y%m%d%H%M%S')}"
            estado_pago = "Pagada" if saldo <= 0 else ("Parcial" if monto_pagado > 0 else "Pendiente")
            metodo_final = metodo_pago if tipo_venta == "Contado" else ("Crédito" if monto_pagado <= 0 else f"Crédito + {metodo_pago}")
            try:
                with ENGINE.begin() as conn:
                    conn.execute(text("""
                        INSERT INTO ventas (comprobante,id_cliente,id_usuario,vendedor_nombre,metodo_pago,total_venta,monto_pagado,saldo_pendiente,estado_pago,observacion,fecha_vencimiento,tipo_venta)
                        VALUES (:comp,:cli,:uid,:vend,:metodo,:total,:pagado,:saldo,:estado,:obs,:venc,:tipo)
                    """), {"comp": comprobante, "cli": opciones_cliente[cliente_nombre], "uid": u["id_usuario"], "vend": u["nombre"], "metodo": metodo_final, "total": total, "pagado": monto_pagado, "saldo": saldo, "estado": estado_pago, "obs": observacion, "venc": str(fecha_venc) if fecha_venc else None, "tipo": tipo_venta})
                    venta_id = int(conn.execute(text("SELECT id_venta FROM ventas WHERE comprobante=:c"), {"c": comprobante}).scalar())
                    for item in st.session_state.cart:
                        subtotal = float(item["cantidad"]) * float(item["precio"])
                        conn.execute(text("""
                            INSERT INTO detalle_ventas (id_venta,id_producto,producto_nombre,cantidad,precio_unitario,costo_unitario,subtotal)
                            VALUES (:idv,:idp,:prod,:cant,:precio,:costo,:sub)
                        """), {"idv": venta_id, "idp": item["id_producto"], "prod": item["nombre"], "cant": item["cantidad"], "precio": item["precio"], "costo": item["costo"], "sub": subtotal})
                        conn.execute(text("""
                            INSERT INTO movimientos_stock (id_producto,tipo,cantidad,costo_unitario,referencia,id_usuario,observacion)
                            VALUES (:idp,'SALIDA_VENTA',:cant,:costo,:ref,:uid,'Venta')
                        """), {"idp": item["id_producto"], "cant": item["cantidad"], "costo": item["costo"], "ref": comprobante, "uid": u["id_usuario"]})
                    if monto_pagado > 0:
                        conn.execute(text("""
                            INSERT INTO caja (tipo,concepto,metodo_pago,monto,referencia,id_usuario,observacion)
                            VALUES ('Ingreso',:concepto,:metodo,:monto,:ref,:uid,:obs)
                        """), {"concepto": f"Venta {comprobante}", "metodo": metodo_pago, "monto": monto_pagado, "ref": comprobante, "uid": u["id_usuario"], "obs": observacion})
                    if tipo_venta == "Crédito" and monto_pagado > 0:
                        conn.execute(text("""
                            INSERT INTO pagos_credito (id_venta,id_cliente,metodo_pago,monto,referencia,id_usuario,observacion)
                            VALUES (:idv,:cli,:metodo,:monto,:ref,:uid,:obs)
                        """), {"idv": venta_id, "cli": opciones_cliente[cliente_nombre], "metodo": metodo_pago, "monto": monto_pagado, "ref": comprobante, "uid": u["id_usuario"], "obs": "Pago inicial"})
                clear_product_cache(); clear_report_cache()
                st.session_state.cart = []
                st.session_state.pos_step = "carrito"
                st.session_state.last_sale_id = venta_id
                st.session_state.show_success_sale = True
                st.rerun()
            except Exception as e:
                st.error("No se pudo registrar la venta.")
                st.exception(e)

def page_productos():
    hero("Productos", "Catálogo visual, imágenes automáticas por código, importación Excel, precios y stock.", "📦")
    productos = productos_con_stock()
    categorias_df = query_df("SELECT * FROM categorias WHERE COALESCE(estado,'Activo')='Activo' ORDER BY nombre_categoria")
    if is_admin():
        tab1, tab2, tab3 = st.tabs(["Catálogo", "Crear / editar", "Importar Excel"])
    else:
        tab1, = st.tabs(["Catálogo"])
        tab2 = tab3 = None
    with tab1:
        c1, c2 = st.columns([1.5, .8])
        with c1:
            buscar = st.text_input("Buscar producto", placeholder="Nombre, código o categoría...", key="buscar_productos")
        with c2:
            cats = sorted([x for x in productos["categoria"].dropna().unique()]) if not productos.empty else []
            cat = st.selectbox("Categoría", ["Todas"] + cats, key="cat_prod")
        fil = productos.copy()
        if buscar.strip():
            txt = buscar.lower()
            fil = fil[fil["nombre_producto"].astype(str).str.lower().str.contains(txt, na=False) | fil["codigo"].astype(str).str.lower().str.contains(txt, na=False) | fil["categoria"].astype(str).str.lower().str.contains(txt, na=False)]
        if cat != "Todas":
            fil = fil[fil["categoria"].eq(cat)]
        if fil.empty:
            st.info("No hay productos.")
        else:
            cols = st.columns(3)
            for i, (_, r) in enumerate(fil.iterrows()):
                with cols[i % 3]:
                    st.markdown(product_card_html(r, show_cost=is_admin(), show_stock=True), unsafe_allow_html=True)
        if not is_admin():
            st.info("Vista de vendedor: puedes consultar productos, precios y stock. La creación y edición quedan reservadas al administrador.")
    if tab2:
        with tab2:
            sub1, sub2 = st.tabs(["Nuevo producto", "Editar producto"])
            cat_opts = {r["nombre_categoria"]: int(r["id_categoria"]) for _, r in categorias_df.iterrows()} if not categorias_df.empty else {}
            with sub1:
                with st.form("form_producto"):
                    a,b = st.columns(2)
                    with a:
                        codigo = st.text_input("Código", placeholder="Ej: 0001")
                        nombre = st.text_input("Nombre del producto")
                        marca = st.text_input("Marca")
                        descripcion = st.text_area("Descripción")
                    with b:
                        categoria = st.selectbox("Categoría", list(cat_opts.keys()) if cat_opts else ["Sin categoría"])
                        costo = st.number_input("Costo unitario", min_value=0.0, step=1.0)
                        precio = st.number_input("Precio de venta", min_value=0.0, step=1.0)
                        stock_min = st.number_input("Stock mínimo", min_value=0.0, step=1.0)
                        stock_ini = st.number_input("Stock inicial", min_value=0.0, step=1.0)
                        imagen_url = st.text_input("Imagen URL opcional")
                    if st.form_submit_button("Guardar producto", type="primary", use_container_width=True):
                        if not nombre.strip():
                            st.error("Ingresa el nombre del producto.")
                        else:
                            codigo_final = normalize_code(codigo) or f"P{datetime.now().strftime('%Y%m%d%H%M%S')}"
                            try:
                                with ENGINE.begin() as conn:
                                    conn.execute(text("""
                                        INSERT INTO productos (codigo,nombre_producto,id_categoria,marca,descripcion,unidad,costo_unitario,precio_venta,stock_minimo,imagen_url,estado)
                                        VALUES (:codigo,:nombre,:cat,:marca,:desc,'Unidad',:costo,:precio,:stock_min,:img,'Activo')
                                    """), {"codigo": codigo_final, "nombre": nombre.strip(), "cat": cat_opts.get(categoria), "marca": marca, "desc": descripcion, "costo": costo, "precio": precio, "stock_min": stock_min, "img": imagen_url})
                                    idp = conn.execute(text("SELECT id_producto FROM productos WHERE codigo=:c"), {"c": codigo_final}).scalar()
                                    if stock_ini > 0:
                                        conn.execute(text("INSERT INTO movimientos_stock (id_producto,tipo,cantidad,costo_unitario,referencia,id_usuario,observacion) VALUES (:idp,'ENTRADA',:cant,:costo,'Stock inicial',:uid,'Alta de producto')"), {"idp": idp, "cant": stock_ini, "costo": costo, "uid": current_user()["id_usuario"]})
                                clear_product_cache(); st.success("Producto guardado."); st.rerun()
                            except Exception as e:
                                st.error("No se pudo guardar. Revisa si el código ya existe.")
            with sub2:
                if productos.empty:
                    st.info("No hay productos para editar.")
                else:
                    opciones = {f"{r['codigo']} - {r['nombre_producto']}": int(r['id_producto']) for _, r in productos.iterrows()}
                    sel = st.selectbox("Producto a editar", list(opciones.keys()))
                    r = productos[productos["id_producto"].eq(opciones[sel])].iloc[0]
                    with st.form("form_editar_producto"):
                        a,b = st.columns(2)
                        with a:
                            nombre = st.text_input("Nombre", value=str(r["nombre_producto"]))
                            marca = st.text_input("Marca", value=str(r.get("marca") or ""))
                            descripcion = st.text_area("Descripción", value=str(r.get("descripcion") or ""))
                            imagen_url = st.text_input("Imagen URL", value=str(r.get("imagen_url") or ""))
                        with b:
                            catnames = list(cat_opts.keys()) if cat_opts else ["Sin categoría"]
                            current_cat = r.get("categoria") if r.get("categoria") in catnames else catnames[0]
                            categoria = st.selectbox("Categoría", catnames, index=catnames.index(current_cat))
                            costo = st.number_input("Costo", min_value=0.0, value=float(r.get("costo_unitario") or 0), step=1.0)
                            precio = st.number_input("Precio", min_value=0.0, value=float(r.get("precio_venta") or 0), step=1.0)
                            stock_min = st.number_input("Stock mínimo", min_value=0.0, value=float(r.get("stock_minimo") or 0), step=1.0)
                            estado = st.selectbox("Estado", ["Activo", "Inactivo"], index=0 if str(r.get("estado","Activo")) == "Activo" else 1)
                        if st.form_submit_button("Actualizar producto", type="primary", use_container_width=True):
                            exec_sql("""
                                UPDATE productos SET nombre_producto=:n, marca=:m, descripcion=:d, id_categoria=:cat, costo_unitario=:costo, precio_venta=:precio, stock_minimo=:sm, imagen_url=:img, estado=:e, actualizado_en=CURRENT_TIMESTAMP
                                WHERE id_producto=:id
                            """, {"n": nombre, "m": marca, "d": descripcion, "cat": cat_opts.get(categoria), "costo": costo, "precio": precio, "sm": stock_min, "img": imagen_url, "e": estado, "id": int(r["id_producto"])})
                            clear_product_cache(); st.success("Producto actualizado."); st.rerun()
    if tab3:
        with tab3:
            st.subheader("Importar productos desde Excel")
            st.write("Descarga la plantilla, llena tus productos y vuelve a subir el archivo. Si el código ya existe, se actualiza.")
            plantilla = pd.DataFrame([{ "codigo":"0001", "nombre":"Producto ejemplo", "categoria":"General", "marca":"", "descripcion":"", "costo":10, "precio":20, "stock":5, "stock_minimo":1, "imagen_url":"", "estado":"Activo" }])
            buf = io.BytesIO()
            with pd.ExcelWriter(buf, engine="openpyxl") as writer:
                plantilla.to_excel(writer, index=False, sheet_name="productos")
            buf.seek(0)
            st.download_button("⬇️ Descargar plantilla Excel", data=buf, file_name="plantilla_productos_clomar_store.xlsx", mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use_container_width=True)
            up = st.file_uploader("Subir Excel de productos", type=["xlsx", "xls"])
            if up:
                df = pd.read_excel(up, dtype={"codigo": str})
                df.columns = [str(c).strip().lower() for c in df.columns]
                required = ["codigo", "nombre", "categoria", "costo", "precio", "stock"]
                missing = [c for c in required if c not in df.columns]
                if missing:
                    st.error(f"Faltan columnas obligatorias: {', '.join(missing)}")
                else:
                    st.write("Vista previa")
                    st.dataframe(df.head(20), use_container_width=True)
                    if st.button("Importar / actualizar productos", type="primary", use_container_width=True):
                        creados = actualizados = categorias_creadas = 0
                        with ENGINE.begin() as conn:
                            for _, row in df.iterrows():
                                codigo = normalize_code(row.get("codigo"))
                                nombre = str(row.get("nombre") or "").strip()
                                if not codigo or not nombre:
                                    continue
                                cat_name = str(row.get("categoria") or "General").strip() or "General"
                                cat_id = conn.execute(text("SELECT id_categoria FROM categorias WHERE nombre_categoria=:n"), {"n": cat_name}).scalar()
                                if not cat_id:
                                    conn.execute(text("INSERT INTO categorias (nombre_categoria, descripcion, estado) VALUES (:n,'Importada desde Excel','Activo')"), {"n": cat_name})
                                    cat_id = conn.execute(text("SELECT id_categoria FROM categorias WHERE nombre_categoria=:n"), {"n": cat_name}).scalar()
                                    categorias_creadas += 1
                                costo = float(row.get("costo") or 0); precio = float(row.get("precio") or 0); stock = float(row.get("stock") or 0)
                                stock_min = float(row.get("stock_minimo") or 0) if "stock_minimo" in df.columns else 0
                                imagen_url = str(row.get("imagen_url") or "").strip() if "imagen_url" in df.columns else ""
                                marca = str(row.get("marca") or "").strip() if "marca" in df.columns else ""
                                desc = str(row.get("descripcion") or "").strip() if "descripcion" in df.columns else ""
                                estado = str(row.get("estado") or "Activo").strip() if "estado" in df.columns else "Activo"
                                idp = conn.execute(text("SELECT id_producto FROM productos WHERE codigo=:c"), {"c": codigo}).scalar()
                                if idp:
                                    conn.execute(text("""
                                        UPDATE productos SET nombre_producto=:n,id_categoria=:cat,marca=:m,descripcion=:d,costo_unitario=:cu,precio_venta=:pv,stock_minimo=:sm,imagen_url=COALESCE(NULLIF(:img,''),imagen_url),estado=:e,actualizado_en=CURRENT_TIMESTAMP WHERE id_producto=:id
                                    """), {"n": nombre, "cat": cat_id, "m": marca, "d": desc, "cu": costo, "pv": precio, "sm": stock_min, "img": imagen_url, "e": estado, "id": idp})
                                    actualizados += 1
                                else:
                                    conn.execute(text("""
                                        INSERT INTO productos (codigo,nombre_producto,id_categoria,marca,descripcion,costo_unitario,precio_venta,stock_minimo,imagen_url,estado)
                                        VALUES (:c,:n,:cat,:m,:d,:cu,:pv,:sm,:img,:e)
                                    """), {"c": codigo, "n": nombre, "cat": cat_id, "m": marca, "d": desc, "cu": costo, "pv": precio, "sm": stock_min, "img": imagen_url, "e": estado})
                                    idp = conn.execute(text("SELECT id_producto FROM productos WHERE codigo=:c"), {"c": codigo}).scalar()
                                    creados += 1
                                current_stock = conn.execute(text(f"SELECT {stock_expr_sql()} FROM movimientos_stock ms WHERE ms.id_producto=:id"), {"id": idp}).scalar() or 0
                                delta = stock - float(current_stock)
                                if abs(delta) > 0.0001:
                                    conn.execute(text("INSERT INTO movimientos_stock (id_producto,tipo,cantidad,costo_unitario,referencia,id_usuario,observacion) VALUES (:id,'AJUSTE',:cant,:cu,'Importación Excel',:uid,'Ajuste de stock desde Excel')"), {"id": idp, "cant": delta, "cu": costo, "uid": current_user()["id_usuario"]})
                        clear_product_cache()
                        st.success(f"Importación terminada. Creados: {creados}. Actualizados: {actualizados}. Categorías nuevas: {categorias_creadas}.")
                        st.rerun()


def filtered_catalog_products():
    productos = productos_con_stock()
    return productos[productos["precio_venta"].astype(float) > 0].copy() if not productos.empty else productos


def page_catalogo_clientes(public=False):
    if not public:
        hero("Catálogo para clientes", "Vista comercial, PDF y consultas por WhatsApp. No muestra costos.", "📘")
    productos = filtered_catalog_products()
    if productos.empty:
        st.info("No hay productos para mostrar.")
        return
    c1, c2, c3 = st.columns([1.2,.8,.5])
    with c1:
        buscar = st.text_input("Buscar en catálogo", placeholder="Nombre, código, categoría...", key="buscar_cat_public" if public else "buscar_cat")
    cats = sorted([x for x in productos["categoria"].dropna().unique()])
    with c2:
        cat = st.selectbox("Categoría", ["Todas"]+cats, key="cat_public" if public else "cat_catalogo")
    with c3:
        solo_stock = st.toggle("Solo con stock", value=True)
    fil = productos.copy()
    if buscar.strip():
        txt = buscar.lower()
        fil = fil[fil["nombre_producto"].astype(str).str.lower().str.contains(txt, na=False) | fil["codigo"].astype(str).str.lower().str.contains(txt, na=False) | fil["categoria"].astype(str).str.lower().str.contains(txt, na=False)]
    if cat != "Todas":
        fil = fil[fil["categoria"].eq(cat)]
    if solo_stock:
        fil = fil[fil["stock_actual"].astype(float) > 0]
    if not public:
        b1,b2,b3 = st.columns(3)
        with b1:
            pdf = generate_catalog_pdf(fil)
            st.download_button("📄 Descargar catálogo PDF", data=pdf or b"", file_name="catalogo_clomar_store.pdf", mime="application/pdf", use_container_width=True, disabled=pdf is None)
        with b2:
            base = (get_setting("catalogo_base_url", "https://clomar-store.streamlit.app") or "").rstrip("/")
            st.link_button("🌐 Abrir catálogo público", f"{base}/?catalogo=1", use_container_width=True)
        with b3:
            st.link_button("💬 WhatsApp tienda", wa_link(), use_container_width=True)
        st.caption(f"Productos visibles: {len(fil)}. El catálogo no muestra costos internos.")
    cols = st.columns(3)
    for i, (_, r) in enumerate(fil.iterrows()):
        with cols[i % 3]:
            st.markdown(product_card_html(r, show_cost=False, show_stock=False, whatsapp=True), unsafe_allow_html=True)


def page_inventario():
    hero("Inventario", "Stock actual, alertas y valorización de mercadería.", "📊")
    if not is_admin():
        st.warning("Solo administrador puede ver inventario completo.")
        return
    productos = productos_con_stock()
    if productos.empty:
        st.info("No hay productos.")
        return
    total_val = (productos["stock_actual"].astype(float) * productos["costo_unitario"].astype(float)).sum()
    total_stock = productos["stock_actual"].astype(float).sum()
    criticos = productos[productos["stock_actual"].astype(float) <= productos["stock_minimo"].astype(float)]
    a,b,c=st.columns(3)
    with a: kpi("Productos", str(len(productos)))
    with b: kpi("Unidades en stock", num(total_stock))
    with c: kpi("Valorización costo", money(total_val))
    view = productos.copy()
    view["precio_fmt"] = view["precio_venta"].apply(money)
    view["costo_fmt"] = view["costo_unitario"].apply(money)
    view["stock_fmt"] = view["stock_actual"].apply(num)
    html_table(view, ["codigo","nombre_producto","categoria","stock_fmt","stock_minimo","costo_fmt","precio_fmt"], ["Código","Producto","Categoría","Stock","Mínimo","Costo","Precio"], 300)
    if not criticos.empty:
        st.warning(f"Hay {len(criticos)} producto(s) en stock crítico.")


def page_ingreso_mercaderia():
    hero("Ingreso de mercadería", "Registra compras, aumenta stock y controla pagos a proveedores.", "📥")
    if not is_admin():
        st.warning("Solo administrador puede registrar ingresos de mercadería.")
        return
    productos = productos_con_stock()
    if productos.empty:
        st.info("Primero registra productos.")
        return
    with st.form("ingreso_mercaderia"):
        proveedor = st.text_input("Proveedor", placeholder="Nombre del proveedor")
        opciones = {f"{r['codigo']} - {r['nombre_producto']} | Stock {num(r['stock_actual'])}": int(r['id_producto']) for _, r in productos.iterrows()}
        prod_sel = st.selectbox("Producto", list(opciones.keys()))
        c1,c2 = st.columns(2)
        with c1:
            cantidad = st.number_input("Cantidad", min_value=0.0, step=1.0)
            costo = st.number_input("Costo unitario", min_value=0.0, step=1.0)
        with c2:
            metodo = st.selectbox("Método de pago", ["Efectivo", "Yape", "Plin", "Transferencia", "Tarjeta", "Crédito"])
            monto_pagado = st.number_input("Monto pagado", min_value=0.0, step=1.0)
        obs = st.text_area("Observación")
        total = cantidad * costo
        kpi("Total de ingreso", money(total), "Costo de mercadería registrada")
        if st.form_submit_button("Registrar ingreso de mercadería", type="primary", use_container_width=True):
            if cantidad <= 0:
                st.error("Cantidad debe ser mayor a cero.")
            else:
                idp = opciones[prod_sel]
                u = current_user()
                ref = f"ING{datetime.now().strftime('%Y%m%d%H%M%S')}"
                with ENGINE.begin() as conn:
                    conn.execute(text("INSERT INTO compras (proveedor,total_compra,monto_pagado,metodo_pago,observacion,id_usuario) VALUES (:p,:t,:mp,:m,:o,:u)"), {"p": proveedor, "t": total, "mp": monto_pagado, "m": metodo, "o": obs, "u": u["id_usuario"]})
                    conn.execute(text("INSERT INTO movimientos_stock (id_producto,tipo,cantidad,costo_unitario,referencia,id_usuario,observacion) VALUES (:id,'ENTRADA_COMPRA',:cant,:costo,:ref,:u,:obs)"), {"id": idp, "cant": cantidad, "costo": costo, "ref": ref, "u": u["id_usuario"], "obs": proveedor})
                    conn.execute(text("UPDATE productos SET costo_unitario=:c, actualizado_en=CURRENT_TIMESTAMP WHERE id_producto=:id"), {"c": costo, "id": idp})
                    if monto_pagado > 0:
                        conn.execute(text("INSERT INTO caja (tipo,concepto,metodo_pago,monto,referencia,id_usuario,observacion) VALUES ('Egreso',:c,:m,:mo,:r,:u,:o)"), {"c": f"Compra {ref}", "m": metodo, "mo": monto_pagado, "r": ref, "u": u["id_usuario"], "o": obs})
                clear_product_cache(); clear_report_cache()
                st.success("Ingreso registrado y stock actualizado.")
                st.rerun()


def page_clientes():
    hero("Clientes", "Registro de clientes, compras y cuentas por cobrar.", "👥")
    with st.expander("Crear cliente"):
        with st.form("cliente_nuevo"):
            nombre = st.text_input("Nombre")
            telefono = st.text_input("Teléfono")
            documento = st.text_input("Documento")
            direccion = st.text_input("Dirección")
            if st.form_submit_button("Guardar cliente", type="primary"):
                if nombre.strip():
                    exec_sql("INSERT INTO clientes (nombre_cliente,telefono,documento,direccion,estado) VALUES (:n,:t,:d,:dir,'Activo')", {"n":nombre,"t":telefono,"d":documento,"dir":direccion})
                    st.success("Cliente guardado."); st.rerun()
                else:
                    st.error("Ingresa el nombre.")
    clientes = query_df("""
        SELECT c.id_cliente,c.nombre_cliente,c.telefono,c.documento,c.direccion,c.estado,
               COALESCE(SUM(v.total_venta),0) total_comprado, COALESCE(SUM(v.saldo_pendiente),0) total_por_cobrar, COUNT(v.id_venta) ventas
        FROM clientes c LEFT JOIN ventas v ON v.id_cliente=c.id_cliente AND COALESCE(v.anulada,0)=0
        GROUP BY c.id_cliente,c.nombre_cliente,c.telefono,c.documento,c.direccion,c.estado
        ORDER BY c.nombre_cliente
    """)
    if clientes.empty:
        st.info("No hay clientes.")
    else:
        cols=st.columns(3)
        for i,(_,r) in enumerate(clientes.iterrows()):
            with cols[i%3]:
                st.markdown(f"<div class='card'><h3>👤 {esc(r['nombre_cliente'])}</h3><div class='product-meta'>{esc(r['telefono'])} · {esc(r['documento'])}</div><span class='chip chip-dark'>Comprado {money(r['total_comprado'])}</span><span class='chip {'chip-red' if float(r['total_por_cobrar'])>0 else 'chip-ok'}'>Por cobrar {money(r['total_por_cobrar'])}</span><span class='chip'>Ventas {int(r['ventas'])}</span></div>", unsafe_allow_html=True)


def page_creditos():
    hero("Créditos / cuentas por cobrar", "Controla ventas pendientes, pagos parciales, saldos y vencimientos.", "💳")
    if not is_admin():
        st.warning("Solo administrador puede ver créditos y cuentas por cobrar.")
        return
    pendientes = query_df("""
        SELECT v.id_venta, v.id_cliente, v.comprobante, v.fecha, v.fecha_vencimiento, v.tipo_venta, v.metodo_pago,
               v.total_venta, v.monto_pagado, v.saldo_pendiente, v.estado_pago,
               COALESCE(c.nombre_cliente,'Cliente general') AS cliente, COALESCE(c.telefono,'') AS telefono
        FROM ventas v
        LEFT JOIN clientes c ON c.id_cliente=v.id_cliente
        WHERE COALESCE(v.anulada,0)=0 AND COALESCE(v.saldo_pendiente,0) > 0
        ORDER BY COALESCE(v.fecha_vencimiento, DATE(v.fecha)) ASC, v.fecha DESC
    """)
    total_pendiente = float(pendientes["saldo_pendiente"].sum()) if not pendientes.empty else 0
    vencidas = 0
    if not pendientes.empty and "fecha_vencimiento" in pendientes.columns:
        fv = pd.to_datetime(pendientes["fecha_vencimiento"], errors="coerce").dt.date
        vencidas = int(((fv < date.today()) & pendientes["saldo_pendiente"].astype(float).gt(0)).sum())
    c1,c2,c3 = st.columns(3)
    with c1: kpi("Total por cobrar", money(total_pendiente), "Saldo pendiente")
    with c2: kpi("Ventas pendientes", str(len(pendientes)), "Créditos abiertos")
    with c3: kpi("Vencidas", str(vencidas), "Requieren seguimiento")

    tab1, tab2, tab3 = st.tabs(["Pendientes", "Registrar pago", "Historial de pagos"])
    with tab1:
        if pendientes.empty:
            st.success("No hay cuentas por cobrar pendientes.")
        else:
            df = pendientes.copy()
            df["total_fmt"] = df["total_venta"].apply(money)
            df["pagado_fmt"] = df["monto_pagado"].apply(money)
            df["saldo_fmt"] = df["saldo_pendiente"].apply(money)
            html_table(df, ["comprobante","fecha","fecha_vencimiento","cliente","telefono","total_fmt","pagado_fmt","saldo_fmt","estado_pago"], ["Comprobante","Fecha","Vence","Cliente","Teléfono","Total","Pagado","Saldo","Estado"], 300)
    with tab2:
        if pendientes.empty:
            st.info("No hay ventas pendientes para registrar pagos.")
        else:
            opts = {}
            for _, r in pendientes.iterrows():
                opts[f"{r['comprobante']} · {r['cliente']} · Saldo {money(r['saldo_pendiente'])}"] = int(r["id_venta"])
            sel = st.selectbox("Venta / cliente", list(opts.keys()))
            venta_sel = pendientes[pendientes["id_venta"].eq(opts[sel])].iloc[0]
            saldo_actual = float(venta_sel["saldo_pendiente"] or 0)
            st.markdown(f"<div class='card'><h3>{esc(venta_sel['cliente'])}</h3><span class='chip chip-red'>Saldo {money(saldo_actual)}</span><span class='chip'>Comprobante {esc(venta_sel['comprobante'])}</span></div>", unsafe_allow_html=True)
            with st.form("form_pago_credito"):
                monto = st.number_input("Monto a pagar", min_value=0.0, max_value=saldo_actual, value=saldo_actual, step=1.0)
                metodo = st.selectbox("Método de pago", ["Efectivo", "Yape", "Plin", "Transferencia", "Tarjeta", "Mixto"])
                obs = st.text_area("Observación", placeholder="Ej: Pago parcial, abono, cancelación...")
                if st.form_submit_button("Registrar pago", type="primary", use_container_width=True):
                    if monto <= 0:
                        st.error("El monto debe ser mayor a cero.")
                    else:
                        nuevo_pagado = float(venta_sel["monto_pagado"] or 0) + monto
                        nuevo_saldo = max(float(venta_sel["total_venta"] or 0) - nuevo_pagado, 0)
                        nuevo_estado = "Pagada" if nuevo_saldo <= 0 else "Parcial"
                        with ENGINE.begin() as conn:
                            conn.execute(text("""
                                UPDATE ventas SET monto_pagado=:pagado, saldo_pendiente=:saldo, estado_pago=:estado
                                WHERE id_venta=:id
                            """), {"pagado": nuevo_pagado, "saldo": nuevo_saldo, "estado": nuevo_estado, "id": int(venta_sel["id_venta"])})
                            conn.execute(text("""
                                INSERT INTO pagos_credito (id_venta,id_cliente,metodo_pago,monto,referencia,id_usuario,observacion)
                                VALUES (:idv,:cli,:metodo,:monto,:ref,:uid,:obs)
                            """), {"idv": int(venta_sel["id_venta"]), "cli": int(venta_sel["id_cliente"]) if "id_cliente" in venta_sel and pd.notna(venta_sel.get("id_cliente")) else None, "metodo": metodo, "monto": monto, "ref": venta_sel["comprobante"], "uid": current_user()["id_usuario"], "obs": obs})
                            conn.execute(text("""
                                INSERT INTO caja (tipo,concepto,metodo_pago,monto,referencia,id_usuario,observacion)
                                VALUES ('Ingreso',:concepto,:metodo,:monto,:ref,:uid,:obs)
                            """), {"concepto": f"Pago crédito {venta_sel['comprobante']}", "metodo": metodo, "monto": monto, "ref": venta_sel["comprobante"], "uid": current_user()["id_usuario"], "obs": obs})
                        clear_report_cache()
                        st.success("Pago registrado correctamente.")
                        st.rerun()
    with tab3:
        pagos = query_df("""
            SELECT pc.fecha, pc.referencia, COALESCE(c.nombre_cliente,'Cliente') AS cliente, pc.metodo_pago, pc.monto, pc.observacion
            FROM pagos_credito pc
            LEFT JOIN clientes c ON c.id_cliente=pc.id_cliente
            ORDER BY pc.fecha DESC
        """)
        if pagos.empty:
            st.info("Todavía no hay pagos de crédito registrados.")
        else:
            pagos["monto_fmt"] = pagos["monto"].apply(money)
            html_table(pagos, ["fecha","referencia","cliente","metodo_pago","monto_fmt","observacion"], ["Fecha","Comprobante","Cliente","Método","Monto","Observación"], 300)

def page_caja():
    hero("Caja", "Movimientos, ingresos, egresos y cierre del día.", "💰")
    if not is_admin():
        st.warning("Solo administrador puede ver caja."); return
    f = st.date_input("Fecha", date.today())
    caja = query_df("SELECT * FROM caja WHERE DATE(fecha)=:f AND COALESCE(anulada,0)=0 ORDER BY fecha DESC", {"f": str(f)})
    ingresos = caja[caja["tipo"].astype(str).str.lower().eq("ingreso")]["monto"].sum() if not caja.empty else 0
    egresos = caja[caja["tipo"].astype(str).str.lower().eq("egreso")]["monto"].sum() if not caja.empty else 0
    a,b,c=st.columns(3)
    with a: kpi("Ingresos", money(ingresos))
    with b: kpi("Egresos", money(egresos))
    with c: kpi("Saldo neto", money(ingresos-egresos))
    if not caja.empty:
        ctab=caja.copy(); ctab["monto_fmt"]=ctab["monto"].apply(money)
        html_table(ctab, ["fecha","tipo","concepto","metodo_pago","monto_fmt","referencia"], ["Fecha","Tipo","Concepto","Pago","Monto","Ref"], 200)
    with st.expander("Registrar egreso / salida"):
        with st.form("egreso"):
            concepto=st.text_input("Concepto")
            monto=st.number_input("Monto", min_value=0.0, step=1.0)
            metodo=st.selectbox("Método", ["Efectivo","Yape","Plin","Transferencia","Tarjeta"])
            if st.form_submit_button("Registrar egreso", type="primary"):
                exec_sql("INSERT INTO caja (tipo,concepto,metodo_pago,monto,id_usuario) VALUES ('Egreso',:c,:m,:mo,:u)", {"c":concepto,"m":metodo,"mo":monto,"u":current_user()["id_usuario"]})
                clear_report_cache(); st.success("Egreso registrado."); st.rerun()


def page_reportes():
    hero("Reportes", "Ventas por fecha, vendedor, producto y método de pago.", "📈")
    if not is_admin():
        st.warning("Solo administrador puede ver reportes."); return
    c1,c2=st.columns(2)
    with c1: desde=st.date_input("Desde", date.today()-timedelta(days=7), key="repd")
    with c2: hasta=st.date_input("Hasta", date.today(), key="reph")
    ventas=ventas_periodo(desde,hasta); detalle=detalle_productos_vendidos(desde,hasta)
    if ventas.empty:
        st.info("No hay ventas en el rango."); return
    ventas["dia"] = pd.to_datetime(ventas["fecha"]).dt.date
    diario = ventas.groupby("dia", as_index=False)["total_venta"].sum()
    fig = px.line(diario, x="dia", y="total_venta", markers=True, title="Ventas por día")
    fig.update_layout(plot_bgcolor="white", paper_bgcolor="white", font_color="#111827")
    st.plotly_chart(fig, use_container_width=True)
    a,b=st.columns(2)
    with a:
        metodo=ventas.groupby("metodo_pago", as_index=False)["total_venta"].sum()
        fig2=px.pie(metodo, names="metodo_pago", values="total_venta", title="Métodos de pago"); fig2.update_layout(paper_bgcolor="white", font_color="#111827")
        st.plotly_chart(fig2, use_container_width=True)
    with b:
        vendedor=ventas.groupby("vendedor_nombre", as_index=False)["total_venta"].sum()
        fig3=px.bar(vendedor, x="vendedor_nombre", y="total_venta", title="Ventas por vendedor"); fig3.update_layout(plot_bgcolor="white", paper_bgcolor="white", font_color="#111827")
        st.plotly_chart(fig3, use_container_width=True)
    if not detalle.empty:
        dd=detalle.copy(); dd["total"]=dd["total_vendido"].apply(money); dd["utilidad_fmt"]=dd["utilidad"].apply(money)
        html_table(dd, ["vendedor","producto","cantidad","total","utilidad_fmt"], ["Vendedor","Producto","Cantidad","Total","Utilidad"], 200)


def page_usuarios():
    hero("Usuarios", "Control de accesos: administrador y vendedor.", "🔐")
    if not is_admin():
        st.warning("Solo administrador puede gestionar usuarios."); return
    tab1, tab2, tab3 = st.tabs(["Lista", "Editar / contraseña", "Crear usuario"])
    with tab1:
        users=query_df("SELECT id_usuario, usuario, nombre, rol, estado, creado_en FROM usuarios ORDER BY id_usuario")
        html_table(users, ["usuario","nombre","rol","estado","creado_en"], ["Usuario","Nombre","Rol","Estado","Creado"], 200)
    with tab2:
        users=query_df("SELECT id_usuario, usuario, nombre, rol, estado FROM usuarios ORDER BY usuario")
        if users.empty:
            st.info("Sin usuarios.")
        else:
            opts={f"{r['usuario']} - {r['nombre']}": int(r['id_usuario']) for _,r in users.iterrows()}
            sel=st.selectbox("Usuario a editar", list(opts.keys()))
            r=users[users["id_usuario"].eq(opts[sel])].iloc[0]
            with st.form("edit_user"):
                nombre=st.text_input("Nombre", value=str(r["nombre"]))
                rol=st.selectbox("Rol", ["Vendedor","Administrador","Supervisor"], index=["Vendedor","Administrador","Supervisor"].index(str(r["rol"])) if str(r["rol"]) in ["Vendedor","Administrador","Supervisor"] else 0)
                estado=st.selectbox("Estado", ["Activo","Inactivo"], index=0 if str(r["estado"])=="Activo" else 1)
                nueva=st.text_input("Nueva contraseña opcional", type="password")
                if st.form_submit_button("Actualizar usuario", type="primary"):
                    params={"n":nombre,"r":rol,"e":estado,"id":int(r["id_usuario"])}
                    exec_sql("UPDATE usuarios SET nombre=:n, rol=:r, estado=:e WHERE id_usuario=:id", params)
                    if nueva:
                        exec_sql("UPDATE usuarios SET password_hash=:p WHERE id_usuario=:id", {"p":hash_password(nueva),"id":int(r["id_usuario"])})
                    st.success("Usuario actualizado."); st.rerun()
    with tab3:
        with st.form("crear_user"):
            usuario=st.text_input("Usuario")
            nombre=st.text_input("Nombre")
            clave=st.text_input("Contraseña", type="password")
            rol=st.selectbox("Rol", ["Vendedor","Administrador","Supervisor"], key="rolnuevo")
            if st.form_submit_button("Crear usuario", type="primary"):
                if not usuario or not clave:
                    st.error("Usuario y contraseña son obligatorios.")
                else:
                    try:
                        exec_sql("INSERT INTO usuarios (usuario,password_hash,nombre,rol,estado) VALUES (:u,:p,:n,:r,'Activo')", {"u":usuario,"p":hash_password(clave),"n":nombre or usuario,"r":rol})
                        st.success("Usuario creado."); st.rerun()
                    except Exception:
                        st.error("No se pudo crear. Quizás el usuario ya existe.")


def page_config_tienda():
    hero("Configuración de tienda", "Personaliza logo, ícono, fotos, datos comerciales y comprobantes.", "⚙️")
    if not is_admin():
        st.warning("Solo administrador puede modificar configuración."); return
    cfg = cached_settings()
    c1,c2=st.columns([1.25,.9])
    with c1:
        with st.form("config_tienda"):
            store_name=st.text_input("Nombre de la tienda", value=cfg.get("store_name", APP_NAME_DEFAULT))
            logo_url=st.text_input("Logo URL", value=cfg.get("logo_url", ""), help="Logo horizontal para login, catálogo y comprobantes.")
            icon_url=st.text_input("Ícono URL", value=cfg.get("icon_url", ""), help="Ícono cuadrado para menú lateral y vista compacta.")
            telefono=st.text_input("Teléfono / WhatsApp", value=cfg.get("telefono", ""))
            direccion=st.text_area("Dirección", value=cfg.get("direccion", ""))
            mensaje=st.text_input("Mensaje del comprobante", value=cfg.get("mensaje_comprobante", "Gracias por su compra."))
            base_cat=st.text_input("URL base de catálogo público", value=cfg.get("catalogo_base_url", "https://clomar-store.streamlit.app"))
            base_imgs=st.text_input("URL base automática de imágenes", value=cfg.get("imagenes_base_url", "https://raw.githubusercontent.com/CLOMARstore/clomar-store/main/imagenes_productos"))
            color=st.color_picker("Color principal", value=cfg.get("color_principal", "#0f172a"))
            if st.form_submit_button("Guardar configuración", type="primary", use_container_width=True):
                for k,v in {"store_name":store_name,"logo_url":logo_url,"icon_url":icon_url,"telefono":telefono,"direccion":direccion,"mensaje_comprobante":mensaje,"catalogo_base_url":base_cat,"imagenes_base_url":base_imgs,"color_principal":color}.items():
                    set_setting(k,v)
                st.success("Configuración guardada."); st.rerun()
    with c2:
        st.subheader("Vista previa")
        if cfg.get("logo_url"):
            st.image(cfg.get("logo_url"), width=220)
        if cfg.get("icon_url"):
            st.image(cfg.get("icon_url"), width=72)
        st.markdown(f"<div class='card'><h2>{esc(cfg.get('store_name') or APP_NAME_DEFAULT)}</h2><div class='product-meta'>{esc(cfg.get('direccion',''))}<br>{esc(cfg.get('telefono',''))}</div><br><span class='chip chip-dark'>Comprobante</span><p>{esc(cfg.get('mensaje_comprobante','Gracias por su compra.'))}</p></div>", unsafe_allow_html=True)
        st.info("V25 usa imágenes automáticas por código. Sube fotos a imagenes_productos/0001.jpg y define la URL base aquí.")


def page_backup():
    hero("Backup / exportación", "Descarga datos de la nube en CSV para respaldo.", "💾")
    if not is_admin():
        st.warning("Solo administrador puede descargar backups."); return
    tablas=["usuarios","categorias","clientes","proveedores","productos","movimientos_stock","ventas","detalle_ventas","compras","caja","ajustes"]
    buffer=io.BytesIO()
    with zipfile.ZipFile(buffer,"w",zipfile.ZIP_DEFLATED) as z:
        for t in tablas:
            try:
                df=query_df(f"SELECT * FROM {t}")
                z.writestr(f"{t}.csv", df.to_csv(index=False).encode("utf-8-sig"))
            except Exception:
                pass
    buffer.seek(0)
    st.download_button("Descargar backup ZIP", data=buffer, file_name=f"clomar_store_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip", mime="application/zip", type="primary")
    st.info("Este ZIP no contiene la contraseña de Neon. Solo exporta datos de negocio.")


def page_instalar_app():
    hero("Instalar como app", "Crea un acceso directo en celular o laptop para abrir Clomar Store como aplicación.", "📲")
    st.markdown("""
    <div class='card'>
      <h3>Android / Chrome</h3>
      <p>1. Abre la app en Chrome.<br>2. Toca los tres puntos.<br>3. Elige <b>Agregar a pantalla principal</b>.<br>4. Confirma el nombre Clomar Store.</p>
      <h3>Windows / Chrome o Edge</h3>
      <p>1. Abre la app en el navegador.<br>2. Menú de tres puntos.<br>3. Apps / Instalar este sitio como app.<br>4. Marca abrir como ventana.</p>
      <p class='small-note'>Esto crea un acceso tipo app. No requiere Play Store ni instalación técnica.</p>
    </div>
    """, unsafe_allow_html=True)


def page_estado_nube():
    hero("Estado nube", "Verifica si la app trabaja local o conectada a PostgreSQL Neon.", "☁️")
    if IS_POSTGRES:
        st.success("Modo nube PostgreSQL activo.")
    else:
        st.warning("Modo local SQLite activo. En Streamlit Cloud debes configurar NEON_DATABASE_URL en Secrets.")
    st.write("Versión:", APP_VERSION)
    st.code("NEON_DATABASE_URL = postgresql://...?...sslmode=require", language="toml")


# ============================================================
# ARRANQUE
# ============================================================
try:
    init_db()
except Exception as e:
    st.error("No se pudo conectar con la base de datos.")
    st.exception(e)
    st.stop()

inject_css()

# Catálogo público por URL
try:
    qp = dict(st.query_params)
except Exception:
    qp = {}
if str(qp.get("catalogo", "")).lower() in ["1", "true", "si", "sí"]:
    cfg = cached_settings()
    st.markdown("<div class='public-wrap'>", unsafe_allow_html=True)
    if cfg.get("logo_url"):
        st.image(cfg.get("logo_url"), width=260)
    hero(cfg.get("store_name") or APP_NAME_DEFAULT, "Catálogo comercial de productos", "🛍️")
    page_catalogo_clientes(public=True)
    st.markdown("</div>", unsafe_allow_html=True)
    st.stop()

if "user" not in st.session_state:
    login_screen()
else:
    selected = sidebar_nav()
    if selected == "📊 Panel dueño": page_panel_dueno()
    elif selected == "🧾 Ventas": page_ventas()
    elif selected == "💳 Créditos": page_creditos()
    elif selected == "📦 Productos": page_productos()
    elif selected == "📘 Catálogo clientes": page_catalogo_clientes()
    elif selected == "📊 Inventario": page_inventario()
    elif selected == "📥 Ingreso mercadería": page_ingreso_mercaderia()
    elif selected == "👥 Clientes": page_clientes()
    elif selected == "💰 Caja": page_caja()
    elif selected == "📈 Reportes": page_reportes()
    elif selected == "🔐 Usuarios": page_usuarios()
    elif selected == "⚙️ Configuración": page_config_tienda()
    elif selected == "💾 Backup": page_backup()
    elif selected == "📲 Instalar app": page_instalar_app()
    elif selected == "☁️ Estado nube": page_estado_nube()
